name: Test and Build Angular UI
run-name: Main Build - ${{ github.actor }} ğŸš€
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Ensure previous builds don't affect this build
      - name: ğŸ§¼ Cleanup
        run: rm -rf dist/

      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ§± Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: â‡ï¸ Install Dependencies
        run: npm ci

      - name: ğŸ§ª Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadlessCI

      - name: ğŸ› ï¸ Build Angular App
        run: npm run build

      - name: ğŸ³ Build Docker Image
        run: docker build -t country-ui:${{ github.sha }} .
